### ISSUE TITLE
3.1.0版本在deepin 15.11版本下卡在启动页面无法打开

### ISSUE THREAD

**Issue by star5o** [zhaopengme/gitnote#293]
3.1.0版本在deepin 15.11版本下卡在启动页面无法打开，并且在命令行下报出以下错误：
```
21:58:42.684 › Error: libcrypto.so.1.0.0: æ æ³æå¼å
±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æç®å½
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_GitNotqHx6Gk/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/tmp/.mount_GitNotqHx6Gk/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
false
```

**Comment by changchang9419** [comment]
我也遇到相同的问题，安装了ssl库就好了。
安装命令如下：
sudo apt-get install libssl1.0.0

**Comment by star5o** [comment]
> 我也遇到相同的问题，安装了ssl库就好了。
> 安装命令如下：
> sudo apt-get install libssl1.0.0

好的，多谢！！

**Comment by A-rafa** [comment]
找了一个untuntu 其他目录下的 ibssl1.0.0， copy 到lib下， 问题解决。
