### ISSUE TITLE
笔记不能于github进行同步

### ISSUE THREAD

**Issue by skyox** [zhaopengme/gitnote#316]
**笔记不能于github进行同步**
创建或修改笔记，不能于同步

**操作系统:**
 - OS: [ Archlinux ]
- gitnote 版本： 3.1.0

** 点击同步按钮，控制台日志**
```
19:03:52.722 › TypeError: Cannot read property 'getStatus' of null
    at e.<anonymous> (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:27828)
    at n (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:697706)
    at Generator._invoke (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:698763)
    at Generator.e.(anonymous function) [as next] (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:697885)
    at r (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:8372)
    at file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:8514
    at new Promise (<anonymous>)
    at new t (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:163312)
    at e.<anonymous> (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:8307)
    at e.j.value (file:///usr/share/gitnote/app.asar/dist/electron/renderer.js:1:28046)
****
```

**Comment by hullhut** [comment]
是作者的服务器挂了?我的打不开了,之前打开也无法同步

**Comment by skyox** [comment]
https://gitnoteapp.com/zh/docs/#git-%E5%90%8C%E6%AD%A5
 linux 测试中

**Comment by ndkrimbacher** [comment]
I have the some problem on a NixOs maschine.
Version 3.1.0

`
TypeError: Cannot read property 'getStatus' of null
    at e.<anonymous> (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:27828)
    at n (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:697706)
    at Generator._invoke (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:698763)
    at Generator.e.(anonymous function) [as next] (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:697885)
    at r (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:8372)
    at file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:8514
    at new Promise (<anonymous>)
    at new t (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:163312)
    at e.<anonymous> (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:8307)
    at e.j.value (file:///nix/store/nj2ws04nxlji8wdpx54r8zzcalf28q7x-gitnote-3.1.0-extracted/resources/app.asar/dist/electron/renderer.js:1:28046)
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:124:28
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:111:28
`

**Comment by lucasjinreal** [comment]
前几天似乎可以同步，现在又不能同步了。
