### ISSUE TITLE
Archlinux卡启动页面，报libcrypto的错

### ISSUE THREAD

**Issue by crisqyxw** [zhaopengme/gitnote#388]
```
18:47:00.120 › Error: libcrypto.so.1.0.0: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_GitNotvd6MW4/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/tmp/.mount_GitNotvd6MW4/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
(node:4476) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 223.75.236.241:443
(node:4476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
看别的issue似乎是要把libssl降级到1.0.0
可是archlinux仓库里最老的版本就是1.1.1.b，这让我怎么降到1.0.0😭

**Comment by ChenSino** [comment]
Manjaro遇到同样的问题
